<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Imbo\\' => array($vendorDir . '/imbo/imbo/library'),
    'ImboUnitTest\\' => array($vendorDir . '/imbo/imbo/tests/phpunit'),
    'ImboIntegrationTest\\' => array($vendorDir . '/imbo/imbo/tests/phpunit'),
    'ImboCli\\' => array($vendorDir . '/imbo/imbo/library'),
    'ImboCliUnitTest\\' => array($vendorDir . '/imbo/imbo/tests/phpunit'),
);
